# Client Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emrah-mern-client
  labels:
    app: emrah-mern-client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: emrah-mern-client
  template:
    metadata:
      labels:
        app: emrah-mern-client
    spec:
      containers:
      - name: client
        image: "{{ .Values.image.client.repository }}:{{ .Values.image.client.tag }}"
        imagePullPolicy: {{ .Values.image.client.pullPolicy }}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: emrah-mern-client
  labels:
    app: emrah-mern-client
spec:
  type: {{ .Values.client.service.type }}
  ports:
  - port: {{ .Values.client.service.port }}
    targetPort: 3000
  selector:
    app: emrah-mern-client

---

# Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emrah-mern-server
  labels:
    app: emrah-mern-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: emrah-mern-server
  template:
    metadata:
      labels:
        app: emrah-mern-server
    spec:
      containers:
      - name: server
        image: "{{ .Values.image.server.repository }}:{{ .Values.image.server.tag }}"
        imagePullPolicy: {{ .Values.image.server.pullPolicy }}
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: emrah-mern-server
  labels:
    app: emrah-mern-server
spec:
  type: {{ .Values.server.service.type }}
  ports:
  - port: {{ .Values.server.service.port }}
    targetPort: 5000
  selector:
    app: emrah-mern-server

---

# Mongo Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emrah-mern-mongo
  labels:
    app: emrah-mern-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emrah-mern-mongo
  template:
    metadata:
      labels:
        app: emrah-mern-mongo
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.image.mongo.repository }}:{{ .Values.image.mongo.tag }}"
        imagePullPolicy: {{ .Values.image.mongo.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mongo.service.port }}
        volumeMounts:
        - mountPath: {{ .Values.mongo.dataPath }}
          name: mongo-data
      volumes:
      - name: mongo-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: emrah-mern-mongo
  labels:
    app: emrah-mern-mongo
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mongo.service.port }}
    targetPort: {{ .Values.mongo.service.port }}
  selector:
    app: emrah-mern-mongo
