apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emrah-mern-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emrah-mern-client
                port:
                  number: {{ .Values.client.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: emrah-mern-server
                port:
                  number: {{ .Values.server.service.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
