apiVersion: apps/v1
kind: Deployment
metadata:
  name: emrah-mern-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emrah-mern-mongo
  template:
    metadata:
      labels:
        app: emrah-mern-mongo
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.image.mongo.repository }}:{{ .Values.image.mongo.tag }}"
        imagePullPolicy: {{ .Values.image.mongo.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mongo.service.port }}
        volumeMounts:
        - mountPath: {{ .Values.mongo.dataPath }}
          name: mongo-data
      volumes:
      - name: mongo-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: emrah-mern-mongo
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mongo.service.port }}
    targetPort: {{ .Values.mongo.service.port }}
  selector:
    app: emrah-mern-mongo
