apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "wordpress.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "wordpress.name" . }}
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: WORDPRESS_DB_HOST
              value: "{{ include "wordpress.fullname" . }}-mysql"
            - name: WORDPRESS_DB_USER
              value: {{ .Values.mysql.mysqlUser }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.mysql.mysqlPassword }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.mysql.mysqlDatabase }}
