{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wordpress.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ index .Values.ingress.hosts 0 "host" | quote }}
      http:
        paths:
          - path: {{ index (index .Values.ingress.hosts 0).paths 0 "path" | quote }}
            pathType: {{ index (index .Values.ingress.hosts 0).paths 0 "pathType" | quote }}
            backend:
              service:
                name: {{ include "wordpress.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
