# values.yaml

replicaCount: 1

image:
  repository: wordpress
  tag: "6.0.2-php8.0-apache"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: wordpress.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# WordPress configurations
wordpressUsername: admin
wordpressPassword: admin
wordpressEmail: admin@example.com
wordpressBlogName: "My Blog"

# MySQL configurations
mysql:
  enabled: true
  image:
    repository: mysql
    tag: "8.0"
  mysqlRootPassword: rootpass
  mysqlUser: wpuser
  mysqlPassword: wppass
  mysqlDatabase: wordpress
  servicePort: 3306
  persistence:
    enabled: true
    size: 5Gi
