# values.yaml

replicaCount: 1

image:
  repository: wordpress
  tag: "6.0.2-php8.0-apache"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: wordpress.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
serviceAccount:
  create: true   # Set to true to create a service account, or false if you want to use an existing one.
  name: ""       # If you want to use a custom service account, specify the name here.
autoscaling:
  enabled: false    # Set to true to enable Horizontal Pod Autoscaler
  minReplicas: 1    # Minimum number of replicas
  maxReplicas: 2   # Maximum number of replicas
  targetCPUUtilizationPercentage: 80  # Target CPU utilization percentage
# WordPress configurations
wordpressUsername: admin
wordpressPassword: admin
wordpressEmail: admin@example.com
wordpressBlogName: "My Blog"

# MySQL configurations
mysql:
  enabled: true
  image:
    repository: mysql
    tag: "8.0"
  mysqlRootPassword: rootpass
  mysqlUser: wpuser
  mysqlPassword: wppass
  mysqlDatabase: wordpress
  servicePort: 3306
  persistence:
    enabled: true
    size: 5Gi

