name: GitHub Actions Demo
run-name: ${{ github.actor }} is learning Terraform and GitHub Actions with RS School 🚀
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write # Required for requesting the JWT token
  contents: read  # Required for actions/checkout
env:
  BUCKET_NAME: "terraformstates-1"
  AWS_REGION: "eu-north-1"
jobs:
  terraform-check:
    name: Check Terraform Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::222634386594:role/GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Run terraform fmt
        working-directory: ./terraform
        run: terraform fmt

      - name: Run terraform fmt check
        run: terraform fmt -check

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: terraform-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::222634386594:role/GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init 

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::222634386594:role/GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init 

      - name: Terraform apply 
        id: apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      # Capture the Terraform output for the private key and store it as a file
      #- name: Get Terraform output
        #id: output
        #working-directory: ./terraform
        #run: echo "::set-output name=k3s_ssh_private_key::$(terraform output -raw k3s_ssh_private_key)"

      #- name: Save private key as artifact
        #####i#f: success()##
        #run: |
          #mkdir -p keys
          #echo "$#{{ steps.output.outputs.k3s_ssh_private_key }}" > keys/k3s-key.pem
          #chmod 600 keys/k3s-key.pem

      #- name: Upload private key artifact
        #uses: actions/upload-artifact@v3
       # with:
          #name: ssh-key
          #path: keys/k3s-key.pem
